BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Companies" (
	"idCompany"	INTEGER NOT NULL UNIQUE,
	"CompanyName"	TEXT NOT NULL,
	PRIMARY KEY("idCompany" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Tags" (
	"idTag"	INTEGER NOT NULL UNIQUE,
	"Tag"	TEXT NOT NULL,
	PRIMARY KEY("idTag" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Tasks" (
	"idTask"	INTEGER NOT NULL UNIQUE,
	"Task"	TEXT NOT NULL,
	"idPosition"	INTEGER NOT NULL,
	"startDate"	TEXT NOT NULL,
	"endDate"	TEXT NOT NULL,
	FOREIGN KEY("idPosition") REFERENCES "Tasks"("idTask"),
	PRIMARY KEY("idTask" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Positions" (
	"idPosition"	INTEGER NOT NULL UNIQUE,
	"Position"	TEXT NOT NULL,
	"idCompany"	INTEGER NOT NULL,
	FOREIGN KEY("idCompany") REFERENCES "Companies"("idCompany"),
	PRIMARY KEY("idPosition" AUTOINCREMENT)
);
COMMIT;
