# Generated by Django 3.2.5 on 2021-08-10 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_auto_20210810_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.RemoveField(
            model_name='position',
            name='company',
        ),
        migrations.AddField(
            model_name='position',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='resume_app.company'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='resume_app.company')),
            ],
        ),
    ]
