# Generated by Django 3.2.5 on 2021-08-10 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0003_auto_20210810_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='company',
        ),
        migrations.AddField(
            model_name='action',
            name='position',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='resume_app.position'),
        ),
    ]
