# Generated by Django 3.2.5 on 2021-08-10 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0005_auto_20210811_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='tag',
            new_name='tag_job',
        ),
    ]
