# Generated by Django 3.2.5 on 2021-08-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0006_rename_tag_action_tag_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.TextField()),
                ('tag_job', models.ManyToManyField(to='resume_app.TagJob')),
            ],
        ),
    ]
