# Generated by Django 3.2.5 on 2021-08-10 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0008_alter_skill_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=24)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('tag_job', models.ManyToManyField(to='resume_app.TagJob')),
            ],
            options={
                'verbose_name_plural': 'education',
            },
        ),
    ]
